name       : python-argon2-cffi
version    : 21.1.0
release    : 1
source     :
    - git|https://github.com/hynek/argon2-cffi.git : 21.1.0
license    : MIT
component  : programming.python
summary    : Secure Password Hashes for Python
description: |
    Argon2 won the Password Hashing Competition and argon2-cffi is the simplest way to use it in Python and PyPy.
builddeps  :
    - pkgconfig(libargon2)
    - pkgconfig(python3)
    - python-cffi
    - python-hypothesis # check
    - python-pytest # check
rundeps    :
    - python-cffi
environment: |
    export ARGON2_CFFI_USE_SSE2=1
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
